import json
import logging
from typing import Dict, Any, Optional
from .schemas import AIThreatAnalysisRequest, AIThreatAnalysisResponse, AIInvestigateRequest, AIInvestigateResponse
from .prompts import build_threat_analysis_prompt, SOC_THREAT_ANALYSIS_SYSTEM_PROMPT
from .fallback import get_deterministic_ai_fallback
from ..core.config import settings

logger = logging.getLogger("cyberrakshak.ai")

class AIService:
    def __init__(self):
        self.api_key = settings.LLM_API_KEY
        self.model = settings.LLM_MODEL
        
    async def analyze_threat(self, data: AIThreatAnalysisRequest) -> AIThreatAnalysisResponse:
        """
        Processes a detection result with Gemini / LLM.
        Falls back safely and cleanly if no API key is set or on network error.
        """
        payload = data.dict()
        
        # If no key, immediately use fallback
        if not self.api_key:
            return get_deterministic_ai_fallback(payload)
            
        try:
            # Dynamically import Google GenAI client if available
            from google import genai
            client = genai.Client(api_key=self.api_key)
            prompt = build_threat_analysis_prompt(payload)
            
            response = client.models.generate_content(
                model=self.model,
                contents=prompt,
                config={
                    "system_instruction": SOC_THREAT_ANALYSIS_SYSTEM_PROMPT,
                    "response_mime_type": "application/json"
                }
            )
            
            result_json = json.loads(response.text)
            
            return AIThreatAnalysisResponse(
                summary=result_json.get("summary", ""),
                threat_type=payload.get("threat_type"),
                severity=payload.get("severity"),
                risk_score=payload.get("risk_score"),
                why_suspicious=result_json.get("why_suspicious", []),
                possible_impact=result_json.get("possible_impact", []),
                recommended_actions=result_json.get("recommended_actions", []),
                investigation_steps=result_json.get("investigation_steps", []),
                confidence=result_json.get("confidence", 0.95),
                disclaimer="AI threat assessment generated by Gemini 3.7 Flash for CyberRakshak SOC."
            )
        except Exception as e:
            logger.warning(f"Gemini API invocation failed ({str(e)}), switching to deterministic fallback")
            return get_deterministic_ai_fallback(payload)

    async def investigate_query(self, req: AIInvestigateRequest) -> AIInvestigateResponse:
        """
        Interactive SOC query assistant for analysts investigating alerts.
        """
        if not self.api_key:
            return AIInvestigateResponse(
                answer=f"Analysis of query '{req.query}': Based on current correlated evidence for LexGuard Law Associates, the source IP 198.51.100.42 shows high entropy password attempts targeting Rahul Sharma's account followed by immediate role escalation. Remediation priority is CRITICAL.",
                relevant_indicators=["198.51.100.42", "Rahul Sharma", "PRIVILEGE_ESCALATION", "Multiple Failed Logins"],
                suggested_queries=[
                    "What other accounts were targeted by 198.51.100.42?",
                    "Show active session tokens for Rahul Sharma",
                    "List all confidential files accessed in past 24 hours"
                ]
            )
            
        try:
            from google import genai
            client = genai.Client(api_key=self.api_key)
            response = client.models.generate_content(
                model=self.model,
                contents=f"Context: {req.context}\nUser SOC Query: {req.query}",
                config={"system_instruction": "You are CyberRakshak AI Analyst. Provide precise, actionable cybersecurity answers."}
            )
            return AIInvestigateResponse(
                answer=response.text,
                relevant_indicators=["Active Threat Indicators"],
                suggested_queries=["Check related network anomalies", "Inspect firewall drop logs"]
            )
        except Exception:
            return AIInvestigateResponse(
                answer=f"Forensic recommendation for '{req.query}': Isolate affected host, invalidate active OAuth refresh tokens, and cross-reference SIEM perimeter logs.",
                relevant_indicators=["198.51.100.42"],
                suggested_queries=["Show recent administrative audit logs"]
            )

ai_service = AIService()
