"""
CyberRakshak Detection Constants
Standardized event types, severities, threat classifications, and risk point weights.
"""

# Event Types
EVENT_LOGIN_FAILED = "LOGIN_FAILED"
EVENT_LOGIN_SUCCESS = "LOGIN_SUCCESS"
EVENT_PRIVILEGE_ESCALATION = "PRIVILEGE_ESCALATION"
EVENT_SUSPICIOUS_IP = "SUSPICIOUS_IP"
EVENT_FILE_ACCESS = "FILE_ACCESS"
EVENT_DATABASE_ACCESS = "DATABASE_ACCESS"
EVENT_COMMAND_EXECUTION = "COMMAND_EXECUTION"
EVENT_LOGOUT = "LOGOUT"

# Threat Classifications
THREAT_BRUTE_FORCE = "BRUTE_FORCE"
THREAT_SUSPICIOUS_LOGIN = "SUSPICIOUS_LOGIN"
THREAT_SUSPICIOUS_IP = "SUSPICIOUS_IP"
THREAT_PRIVILEGE_ESCALATION = "PRIVILEGE_ESCALATION"
THREAT_SENSITIVE_DATA_ACCESS = "SENSITIVE_DATA_ACCESS"
THREAT_POTENTIAL_ACCOUNT_COMPROMISE = "POTENTIAL_ACCOUNT_COMPROMISE"

# Severity Levels
SEVERITY_LOW = "LOW"
SEVERITY_MEDIUM = "MEDIUM"
SEVERITY_HIGH = "HIGH"
SEVERITY_CRITICAL = "CRITICAL"
SEVERITY_INFO = "INFO"

# Deterministic Risk Scoring Weights
RISK_WEIGHT_REPEATED_FAILED_LOGIN = 25
RISK_WEIGHT_SUCCESSFUL_LOGIN_AFTER_FAILURES = 20
RISK_WEIGHT_SUSPICIOUS_IP = 20
RISK_WEIGHT_PRIVILEGE_ESCALATION = 30
RISK_WEIGHT_SENSITIVE_DATA_ACCESS = 20

# Known Suspicious IPs for MVP Reputation Checking
KNOWN_SUSPICIOUS_IPS = {
    "198.51.100.42",
    "203.0.113.195",
    "185.220.101.5",
    "45.154.255.89",
    "194.26.29.112",
    "103.251.167.20"
}
